# create volumes for mariadb and wordpress

- name: Create volumes for WordPress and MariaDB
  file:
    path: "{{ ansible_env.HOME }}/data/wordpress"
    state: directory
- name: Create volumes for WordPress and MariaDB
  file:
    path: "{{ ansible_env.HOME }}/data/mariadb"
    state: directory

- name: Copy docker-compose.yml
  copy:
    src:  docker-compose.yml
    dest: "{{ ansible_env.HOME }}/cloud-1-abouassi/docker-compose.yml"
    mode: '0644'
- name: Copy .env file
  copy:
    src: .env
    dest: "{{ ansible_env.HOME }}/cloud-1-abouassi/.env"
    mode: '0644'

- name: Run docker-compose
  command: 	docker-compose -f docker-compose.yml up -d --build
  args:
    chdir: "{{ ansible_env.HOME }}/cloud-1-abouassi"
